# Site settings
title: Dev Blog
description: 'Keeping track of past and future projects'
url: 'https://areeb-m.github.io/dev-blog/'
baseurl: '/dev-blog'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Areeb Mohammed'
#  email: josh@joshgerdes.com
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username:  Areeb-M
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
